#! /bin/sh

picom --experimental-backends &
pgrep -x redshift > /dev/null || redshift -l 33.89:151.21 &
dunst &
nm-applet &
feh --randomize --bg-fill ~/Pictures/wallpapers/* &
xsetroot -cursor_name left_ptr &
xinput --set-prop 'pointer:Logitech G Pro' 'libinput Accel Profile Enabled' 0, 1

xrandr --output DP-2 --primary --mode 1920x1080 --rate 144 --output HDMI-3 --mode 1920x1080 --left-of DP-2
~/.config/polybar/launch.sh &
pkill sxhkd
sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-3 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width                  2
bspc config window_gap                    4

bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc config focus_follows_pointer         true
bspc config pointer_motion_interval       7

bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating
bspc rule -a Zoom state=floating

