#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom --experimental-backends &
xset -dpms s off &
pgrep -x redshift > /dev/null || redshift -l 33.89:151.21 &
dunst &
pgrep -f i3-battery-popup > /dev/null || i3-battery-popup -n &
~/.config/polybar/launch.sh &
nm-applet &
feh --randomize --bg-fill ~/Pictures/wallpapers/* &
xsetroot -cursor_name left_ptr &

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
		let name++
	done
}
workspaces

bspc config border_width                  2
bspc config window_gap                    4

bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc config focus_follows_pointer         true
bspc config pointer_motion_interval       7

bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating
bspc rule -a Zoom state=floating
