displays:
  - name: eDP
    workspaces: [1,2,3]
  - name: DisplayPort-1
    workspaces: [4,5,6]
    randr_extra_options: "--left-of eDP"
  - name: HDMI-A-0
    workspaces: [7,8,9]
    randr_extra_options: "--left-of DisplayPort-1"

