#!/bin/bash

CONFIG_FILES="$HOME/.config/waybar/config $HOME/.config/waybar/style.css"

trap "killall waybar" EXIT

while true; do
    clear && waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
